fix(falco/readme): use rules_files instead of deprecated rules_file in config snippet
Using rules_file causes collision with rules_files and falco does not start

```
Tue Nov 12 14:23:17 2024: Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
Error: Error reading config file (/etc/falco/falco.yaml): both 'rules_files' and 'rules_file' keys set
```

Signed-off-by: Robin Landström <robinlandstrom@users.noreply.github.com>